package pl.piomin.signalmind.signal.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import pl.piomin.signalmind.stock.domain.Stock;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * A trading signal generated by a {@link pl.piomin.signalmind.signal.detector.SignalDetector}.
 *
 * <p>Maps to the {@code signals} table, which was created in V4 and extended
 * in V10 to add ORB-specific columns ({@code target2}, {@code orb_high}, {@code orb_low}).
 *
 * <p>The dispatch lifecycle fields ({@code dispatched}, {@code dispatchedAt}) and the
 * intraday status ({@code status}, SM-31) are mutable after creation; all other fields
 * are set once in the constructor and immutable.
 */
@Entity
@Table(name = "signals")
public class Signal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "stock_id", nullable = false)
    private Stock stock;

    @Enumerated(EnumType.STRING)
    @Column(name = "signal_type", nullable = false, length = 30)
    private SignalType signalType;

    @Enumerated(EnumType.STRING)
    @Column(name = "direction", nullable = false, length = 5)
    private SignalDirection direction;

    @Column(name = "entry_price", nullable = false, precision = 12, scale = 2)
    private BigDecimal entryPrice;

    /** T1 — primary profit target. */
    @Column(name = "target_price", nullable = false, precision = 12, scale = 2)
    private BigDecimal targetPrice;

    /** T2 — secondary profit target; nullable for signal types that do not set it. */
    @Column(name = "target2", precision = 12, scale = 2)
    private BigDecimal target2;

    @Column(name = "stop_loss", nullable = false, precision = 12, scale = 2)
    private BigDecimal stopLoss;

    @Column(name = "confidence", nullable = false)
    private int confidence;

    @Column(name = "regime", nullable = false, length = 20)
    private String regime;

    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;

    @Column(name = "valid_until", nullable = false)
    private Instant validUntil;

    @Column(name = "dispatched", nullable = false)
    private boolean dispatched = false;

    @Column(name = "dispatched_at")
    private Instant dispatchedAt;

    /** Opening-range high; populated by the ORB detector, null for other signal types. */
    @Column(name = "orb_high", precision = 12, scale = 2)
    private BigDecimal orbHigh;

    /** Opening-range low; populated by the ORB detector, null for other signal types. */
    @Column(name = "orb_low", precision = 12, scale = 2)
    private BigDecimal orbLow;

    // ── SM-26 Confidence Scoring breakdown ────────────────────────────────────

    /** Base pattern-quality component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_base")
    private Integer scoreBase;

    /** Volume-confirmation component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_volume")
    private Integer scoreVolume;

    /** Time-of-day component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_time_of_day")
    private Integer scoreTimeOfDay;

    /** Market-regime component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_regime")
    private Integer scoreRegime;

    /** Historical win-rate component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_win_rate")
    private Integer scoreWinRate;

    /** Multi-indicator confluence component of the confidence score (SM-26). Null until {@link #applyScores} is called. */
    @Column(name = "score_confluence")
    private Integer scoreConfluence;

    // ── SM-31: Intraday signal status ─────────────────────────────────────────

    /**
     * Current lifecycle status of this signal (SM-31).
     * Starts as {@link SignalStatus#GENERATED} and transitions via
     * {@link SignalStatusService} as prices move intraday.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private SignalStatus status = SignalStatus.GENERATED;

    // ── Constructors ──────────────────────────────────────────────────────────

    /** Required by JPA. Not for application use. */
    protected Signal() {
    }

    /**
     * Full constructor used by signal detectors.
     *
     * @param stock       the stock this signal is for
     * @param signalType  detector classification (e.g. ORB)
     * @param direction   LONG or SHORT
     * @param entryPrice  recommended entry price
     * @param targetPrice T1 profit target
     * @param target2     T2 profit target (may be null for non-ORB signals)
     * @param stopLoss    stop-loss level
     * @param confidence  score 0–100 (clamped by caller)
     * @param regime      market regime name at generation time
     * @param generatedAt timestamp when the breakout candle closed
     * @param validUntil  signal expiry (typically generatedAt + 15 min)
     * @param orbHigh     opening-range high (null for non-ORB detectors)
     * @param orbLow      opening-range low (null for non-ORB detectors)
     */
    public Signal(Stock stock, SignalType signalType, SignalDirection direction,
                  BigDecimal entryPrice, BigDecimal targetPrice, BigDecimal target2,
                  BigDecimal stopLoss, int confidence, String regime,
                  Instant generatedAt, Instant validUntil,
                  BigDecimal orbHigh, BigDecimal orbLow) {
        this.stock = stock;
        this.signalType = signalType;
        this.direction = direction;
        this.entryPrice = entryPrice;
        this.targetPrice = targetPrice;
        this.target2 = target2;
        this.stopLoss = stopLoss;
        this.confidence = confidence;
        this.regime = regime;
        this.generatedAt = generatedAt;
        this.validUntil = validUntil;
        this.orbHigh = orbHigh;
        this.orbLow = orbLow;
    }

    // ── Dispatch lifecycle ────────────────────────────────────────────────────

    /**
     * Marks the signal as dispatched to the notification channel.
     * Sets both {@code dispatched = true} and records the timestamp.
     *
     * @param now the instant at which the dispatch was confirmed
     */
    public void markDispatched(Instant now) {
        this.dispatched = true;
        this.dispatchedAt = now;
    }

    // ── SM-26 Confidence Scoring ──────────────────────────────────────────────

    /**
     * Applies the SM-26 confidence scoring breakdown.
     * Overwrites the rough confidence set at construction time with the fully-scored value.
     *
     * @param base       base pattern-quality points
     * @param volume     volume-confirmation points
     * @param timeOfDay  time-of-day points
     * @param regime     market-regime points
     * @param winRate    historical win-rate points
     * @param confluence multi-indicator confluence points
     */
    public void applyScores(int base, int volume, int timeOfDay, int regime, int winRate, int confluence) {
        this.scoreBase = base;
        this.scoreVolume = volume;
        this.scoreTimeOfDay = timeOfDay;
        this.scoreRegime = regime;
        this.scoreWinRate = winRate;
        this.scoreConfluence = confluence;
        this.confidence = Math.min(100, base + volume + timeOfDay + regime + winRate + confluence);
    }

    // ── SM-31: Status lifecycle ───────────────────────────────────────────────

    /**
     * Transitions this signal to a new intraday status.
     * Called exclusively by {@link SignalStatusService}.
     *
     * @param newStatus the status to transition to
     */
    public void updateStatus(SignalStatus newStatus) {
        this.status = newStatus;
    }

    // ── Setters (dispatch only) ───────────────────────────────────────────────

    public void setDispatched(boolean dispatched) {
        this.dispatched = dispatched;
    }

    public void setDispatchedAt(Instant dispatchedAt) {
        this.dispatchedAt = dispatchedAt;
    }

    // ── Getters ───────────────────────────────────────────────────────────────

    public Long getId() {
        return id;
    }

    public Stock getStock() {
        return stock;
    }

    public SignalType getSignalType() {
        return signalType;
    }

    public SignalDirection getDirection() {
        return direction;
    }

    public BigDecimal getEntryPrice() {
        return entryPrice;
    }

    public BigDecimal getTargetPrice() {
        return targetPrice;
    }

    public BigDecimal getTarget2() {
        return target2;
    }

    public BigDecimal getStopLoss() {
        return stopLoss;
    }

    public int getConfidence() {
        return confidence;
    }

    public String getRegime() {
        return regime;
    }

    public Instant getGeneratedAt() {
        return generatedAt;
    }

    public Instant getValidUntil() {
        return validUntil;
    }

    public boolean isDispatched() {
        return dispatched;
    }

    public Instant getDispatchedAt() {
        return dispatchedAt;
    }

    public BigDecimal getOrbHigh() {
        return orbHigh;
    }

    public BigDecimal getOrbLow() {
        return orbLow;
    }

    public Integer getScoreBase() {
        return scoreBase;
    }

    public Integer getScoreVolume() {
        return scoreVolume;
    }

    public Integer getScoreTimeOfDay() {
        return scoreTimeOfDay;
    }

    public Integer getScoreRegime() {
        return scoreRegime;
    }

    public Integer getScoreWinRate() {
        return scoreWinRate;
    }

    public Integer getScoreConfluence() {
        return scoreConfluence;
    }

    public SignalStatus getStatus() {
        return status;
    }

    @Override
    public String toString() {
        return "Signal{id=" + id
                + ", stock=" + (stock != null ? stock.getSymbol() : "?")
                + ", type=" + signalType
                + ", direction=" + direction
                + ", entry=" + entryPrice
                + ", confidence=" + confidence + "}";
    }
}
